/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemadeemergencias;

import java.awt.Color;
import java.awt.Graphics;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.stream.Stream;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author Castro
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    static Grafo gr = new Grafo();
    static Dibujar dj=new Dibujar();
    static Kruskal k = new Kruskal();
    static Graphics line;
    static Prim p = new Prim();
    static int[][] Matriz = gr.getG();

    public Ventana() {

        initComponents();
    }

    public int IngresarNodo() {
        int nodoOrigen = 0;
        String menu = "0)Primer" + '\n' + "1)Segunda" + '\n' + "2)Tercera" + '\n' + "3)Cuarta" + '\n' + "4)Quinta" + '\n' + "5)Sexta";
        JOptionPane.showMessageDialog(null, "" + menu + "\nDebe de ingresar  una Ciudad existente");
        nodoOrigen = Integer.parseInt(JOptionPane.showInputDialog("#ingresar la ciudad"));

        return nodoOrigen;
    }

    public void Pintar(int i) {

        if (0 == i) {

            jpn0.setBackground(Color.red);

        } else if (i == 1) {
            jpn1.setBackground(Color.red);

        } else if (i == 2) {
            jpn2.setBackground(Color.red);

        } else if (i == 3) {
            jpn3.setBackground(Color.red);
        } else if (i == 4) {
            jpn4.setBackground(Color.red);
        } else if (i == 5) {
            jpn5.setBackground(Color.red);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpn0 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpn3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Tools = new javax.swing.JToolBar();
        btn_anchura1 = new javax.swing.JButton();
        btn_profundidad = new javax.swing.JButton();
        btn_Prim = new javax.swing.JButton();
        btn_Kruskal = new javax.swing.JButton();
        btnEuler = new javax.swing.JButton();
        jpn2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jpn5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jpn4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jpn1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblRecorrido = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jbResultado = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpn0.setBackground(new java.awt.Color(255, 255, 153));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("a");

        javax.swing.GroupLayout jpn0Layout = new javax.swing.GroupLayout(jpn0);
        jpn0.setLayout(jpn0Layout);
        jpn0Layout.setHorizontalGroup(
            jpn0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpn0Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpn0Layout.setVerticalGroup(
            jpn0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn0Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpn3.setBackground(new java.awt.Color(255, 255, 153));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("d");

        javax.swing.GroupLayout jpn3Layout = new javax.swing.GroupLayout(jpn3);
        jpn3.setLayout(jpn3Layout);
        jpn3Layout.setHorizontalGroup(
            jpn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpn3Layout.setVerticalGroup(
            jpn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        Tools.setRollover(true);

        btn_anchura1.setText("Anchura");
        btn_anchura1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_anchura1ActionPerformed(evt);
            }
        });
        Tools.add(btn_anchura1);

        btn_profundidad.setText("Profundidad");
        btn_profundidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_profundidadActionPerformed(evt);
            }
        });
        Tools.add(btn_profundidad);

        btn_Prim.setText("Busqueda de prim");
        btn_Prim.setFocusable(false);
        btn_Prim.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Prim.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_Prim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PrimActionPerformed(evt);
            }
        });
        Tools.add(btn_Prim);

        btn_Kruskal.setText("Busqueda Kruskal");
        btn_Kruskal.setFocusable(false);
        btn_Kruskal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Kruskal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_Kruskal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KruskalActionPerformed(evt);
            }
        });
        Tools.add(btn_Kruskal);

        btnEuler.setText("Euler");
        btnEuler.setFocusable(false);
        btnEuler.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEuler.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEulerActionPerformed(evt);
            }
        });
        Tools.add(btnEuler);

        jpn2.setBackground(new java.awt.Color(255, 255, 153));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("c");

        javax.swing.GroupLayout jpn2Layout = new javax.swing.GroupLayout(jpn2);
        jpn2.setLayout(jpn2Layout);
        jpn2Layout.setHorizontalGroup(
            jpn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpn2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpn2Layout.setVerticalGroup(
            jpn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        jpn5.setBackground(new java.awt.Color(255, 255, 153));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("f");

        javax.swing.GroupLayout jpn5Layout = new javax.swing.GroupLayout(jpn5);
        jpn5.setLayout(jpn5Layout);
        jpn5Layout.setHorizontalGroup(
            jpn5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpn5Layout.setVerticalGroup(
            jpn5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpn4.setBackground(new java.awt.Color(255, 255, 153));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("e");

        javax.swing.GroupLayout jpn4Layout = new javax.swing.GroupLayout(jpn4);
        jpn4.setLayout(jpn4Layout);
        jpn4Layout.setHorizontalGroup(
            jpn4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpn4Layout.setVerticalGroup(
            jpn4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpn4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpn1.setBackground(new java.awt.Color(255, 255, 153));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("b");

        javax.swing.GroupLayout jpn1Layout = new javax.swing.GroupLayout(jpn1);
        jpn1.setLayout(jpn1Layout);
        jpn1Layout.setHorizontalGroup(
            jpn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpn1Layout.setVerticalGroup(
            jpn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblRecorrido.setText("Recorrido");

        jbResultado.setEditable(false);
        jbResultado.setColumns(20);
        jbResultado.setRows(5);
        jScrollPane2.setViewportView(jbResultado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(lblRecorrido))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jpn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(203, 203, 203)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpn4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpn5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpn0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(148, 148, 148))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(Tools, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Tools, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpn0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jpn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(193, 193, 193))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jpn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpn5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblRecorrido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_anchura1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_anchura1ActionPerformed
        // TODO add your handling code here:
        int nodo = IngresarNodo();

        try {
            ArrayList<Integer> cola = gr.recorridoAnchura(nodo);
            System.out.println("Anchura");

            String m = "";

            for (int i = 0; i < cola.size(); i++) {
                System.out.println(cola.get(i));
                m = m + "->" + cola.get(i) + '\r' + '\n';
                Pintar(i);
                try {
                    Thread.sleep(1000);
                    Pintar(i);
                } catch (Exception e) {

                }

            }
            lblRecorrido.setText("Recorrido Anchura");
            jbResultado.setText(m);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(new JFrame(), "Erorr", "", JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_btn_anchura1ActionPerformed

    private void btn_profundidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_profundidadActionPerformed
        // TODO add your handling code here:
        int nodo = IngresarNodo();
        try {

            ArrayList<Integer> pr = gr.recorridoProfundidad(nodo);
            String m = "";
            System.out.println("Profundidad");
            for (int x = 0; x < pr.size(); x++) {
                System.out.println(pr.get(x));
                m = m + "->" + pr.get(x) + '\r' + '\n';
                lblRecorrido.setText("Recorrido Profundidad");
                jbResultado.setText(m);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(new JFrame(), "Erorr", "", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_profundidadActionPerformed

    private void btn_PrimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PrimActionPerformed
        // TODO add your handling code here:

        System.out.println("MATRIZ ORIGINAL");
        for (int contadorHorizontal = 0; contadorHorizontal < Matriz[0].length; contadorHorizontal++) {
            for (int contadorVertical = 0; contadorVertical < Matriz[0].length; contadorVertical++) {
                System.out.print(Matriz[contadorHorizontal][contadorVertical] + "   ");
            }
            System.out.println();
        }
        String pantalla = "";
     
        /**
        *Invokamos la funcion Prim y le pasamos como parametro la matriz a la cual aplicaremos
        * el algoritmo de Prim
        */
        int [][] MatrizFinal = p.Algoritmo_Prim(Matriz);
        
        /**
        *Impresion de matriz Final
        */
        System.out.println("MATRIZ RESULTANTE");
        for(int contadorHorizontal = 0; contadorHorizontal < MatrizFinal[0].length;contadorHorizontal++)
        {
            for(int contadorVertical = 0;contadorVertical < MatrizFinal[0].length;contadorVertical++)
            {
                System.out.print(MatrizFinal[contadorHorizontal][contadorVertical] + "   ");
            }
            System.out.println();
        }
     
       /* System.out.println("Verices visitados: ");
        for(int i=0;i<p.nodosAdyacentes.size();i++){
            System.out.println("->"+p.nodosAdyacentes.get(i));
        
        }
         System.out.println("Verices visitados: ");
        for(int i=0;i<p.verticesVisitados.size();i++){
            System.out.println("->"+p.verticesVisitados.get(i));
        
        }*/
        System.out.println("Arista Distancia: ");
        for(int i=0;i<p.distanciasRelativas.size();i++){
            System.out.println("->"+p.distanciasRelativas.get(i));
        
        }
    
        lblRecorrido.setText("Recorrido de Prim");
        jbResultado.setText(pantalla);
    }//GEN-LAST:event_btn_PrimActionPerformed

    private void btn_KruskalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KruskalActionPerformed
        // TODO add your handling code here:
        k.Algoritmo(Matriz);
        dj.getClass();

    }//GEN-LAST:event_btn_KruskalActionPerformed

    private void btnEulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEulerActionPerformed
        // TODO add your handling code here:
       boolean dirigido=false; 

	Euler A = new Euler();
	System.out.println("CIRCUITO EULERIANO");
        try {
            
        
        ArrayList<Integer> resultado = null;

	if(dirigido)
	    {
		if(A.camino_eulerGD(Matriz,0,0))
		    resultado =A.mostrar_euler();
	    }
	else
	    {
		if(A.camino_eulerGND(Matriz,0,0))
		    resultado =A.mostrar_euler();
	    }
        
       for(int i=0;i<resultado.size();i++){
           System.out.println(resultado.get(i));
       
       }
    } catch (Exception e) {
          JOptionPane.showMessageDialog(new JFrame(), "En este momento no esta disponible esta opcion", "Erorr", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEulerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
     
                
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar Tools;
    private javax.swing.JButton btnEuler;
    private javax.swing.JButton btn_Kruskal;
    private javax.swing.JButton btn_Prim;
    private javax.swing.JButton btn_anchura1;
    private javax.swing.JButton btn_profundidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jbResultado;
    private javax.swing.JPanel jpn0;
    private javax.swing.JPanel jpn1;
    private javax.swing.JPanel jpn2;
    private javax.swing.JPanel jpn3;
    private javax.swing.JPanel jpn4;
    private javax.swing.JPanel jpn5;
    private javax.swing.JLabel lblRecorrido;
    // End of variables declaration//GEN-END:variables
}
