/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinaldb;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import logica.Conexion;

/**
 *
 * @author Castro
 */
public class VentanaProcedimientos extends javax.swing.JFrame {

    /**
     * Creates new form ventanaProcedimientos
     */
 Conexion str_conn = new Conexion() ;
    public VentanaProcedimientos() {
        initComponents();
            
      
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cb_tipo = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_nombreP = new javax.swing.JTextField();
        txt_valor = new javax.swing.JTextField();
        btn_ejecutar = new javax.swing.JButton();
        txt_procedimiento = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_entradas = new javax.swing.JTable();
        btn_agregar1 = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_result = new javax.swing.JTable();
        btn_conexion = new javax.swing.JButton();
        btn_procedimientos = new javax.swing.JButton();
        btn_datos = new javax.swing.JButton();
        btn_sqlsentence = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cb_tipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Procedimiento", "Funcion" }));
        cb_tipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_tipoItemStateChanged(evt);
            }
        });

        jLabel1.setText("Tipo");

        jLabel2.setText("Procedimiento");

        jLabel3.setText("Nombre");

        jLabel4.setText("Parametro");

        jLabel5.setText("Valor");

        btn_ejecutar.setText("Ejecutar");
        btn_ejecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ejecutarActionPerformed(evt);
            }
        });

        tbl_entradas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_entradas.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tbl_entradas);
        tbl_entradas.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        if (tbl_entradas.getColumnModel().getColumnCount() > 0) {
            tbl_entradas.getColumnModel().getColumn(0).setResizable(false);
        }

        btn_agregar1.setText("Agregar");
        btn_agregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregar1ActionPerformed(evt);
            }
        });

        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        tbl_result.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Resultado"
            }
        ));
        jScrollPane2.setViewportView(tbl_result);

        btn_conexion.setText("String Conexion");
        btn_conexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_conexionActionPerformed(evt);
            }
        });

        btn_procedimientos.setText("Procedimientos");
        btn_procedimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_procedimientosActionPerformed(evt);
            }
        });

        btn_datos.setText("Datos Personales");
        btn_datos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_datosActionPerformed(evt);
            }
        });

        btn_sqlsentence.setText("SQL Dinamico");
        btn_sqlsentence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sqlsentenceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btn_conexion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_procedimientos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_datos))
                    .addComponent(btn_sqlsentence, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(btn_agregar1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(263, 263, 263)
                        .addComponent(btn_ejecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_nombreP, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(cb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(23, 23, 23)
                        .addComponent(txt_procedimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(cb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txt_procedimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btn_datos)
                        .addGap(18, 18, 18)
                        .addComponent(btn_conexion)
                        .addGap(18, 18, 18)
                        .addComponent(btn_procedimientos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_sqlsentence))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel4)
                                .addGap(16, 16, 16)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(txt_nombreP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(txt_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_agregar1)
                            .addComponent(btn_ejecutar))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_eliminar)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregar1ActionPerformed
        // TODO add your handling code here:
    Object [] fila = new Object[2];
    DefaultTableModel modelo=(DefaultTableModel) tbl_entradas.getModel();
     fila[0]= txt_nombreP.getText();
     fila[1]=txt_valor.getText();
  
     modelo.addRow(fila);
     
     tbl_entradas.setModel(modelo);
    
   
    }//GEN-LAST:event_btn_agregar1ActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        // TODO add your handling code here:
             DefaultTableModel model = (DefaultTableModel) tbl_entradas.getModel(); 
         //Sección 2
          int a = tbl_entradas.getSelectedRow(); 
         //Sección 3
          if (a<0){ 
                JOptionPane.showMessageDialog(null, 

                "Debe seleccionar una fila de la tabla, haz click sobre ella" ); 
         }else {          
           //Sección 4
            int confirmar=JOptionPane.showConfirmDialog(null, 

           "Esta seguro que desea Eliminar el registro? ");
            //Sección 5 
        if(JOptionPane.OK_OPTION==confirmar) {                  

                  //Sección 6
                   model.removeRow(a); 
                  //Sección 7
                   JOptionPane.showMessageDialog(null,"Registro Eliminado" );

 

            } 

 

        } 
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_ejecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ejecutarActionPerformed
        // TODO add your handling code here:
           String texto= cb_tipo.getSelectedItem().toString();
           String name= txt_procedimiento.getText().trim().toString();
            if(texto.equals("Procedimiento")){
           DefaultTableModel modelo=(DefaultTableModel) tbl_entradas.getModel();
         
           
           
             DefaultTableModel rs= str_conn.Procedimientos(modelo,name);
            
             tbl_result.setModel(rs);
            }
            if(texto.equals("Funcion")){
            
           str_conn.funciones(name);
            }
    }//GEN-LAST:event_btn_ejecutarActionPerformed

    private void btn_conexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_conexionActionPerformed
        // TODO add your handling code here:
        VentanaConexion strConexion = new VentanaConexion();

        strConexion.setVisible(true);
    }//GEN-LAST:event_btn_conexionActionPerformed

    private void btn_procedimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_procedimientosActionPerformed
        // TODO add your handling code here:
        VentanaProcedimientos pro = new VentanaProcedimientos();
        pro.setVisible(true);
    }//GEN-LAST:event_btn_procedimientosActionPerformed

    private void btn_datosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_datosActionPerformed
        // TODO add your handling code here:
        VentanaDatos vd= new VentanaDatos();
        vd.setVisible(true);
    }//GEN-LAST:event_btn_datosActionPerformed

    private void btn_sqlsentenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sqlsentenceActionPerformed
        // TODO add your handling code here:
         VentanaSQLDinamico d= new  VentanaSQLDinamico();
            d.setVisible(true);
    }//GEN-LAST:event_btn_sqlsentenceActionPerformed

    private void cb_tipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_tipoItemStateChanged
        // TODO add your handling code here:
        String texto= cb_tipo.getSelectedItem().toString();
       
        if(texto.equals("Funcion")){
        txt_nombreP.setEnabled(false);
        txt_valor.setEnabled(false);
        btn_eliminar.setEnabled(false);
        btn_agregar1.setEnabled(false);
        
        }
        if(texto.equals("Procedimiento")){
        
         txt_nombreP.setEnabled(true);
        txt_valor.setEnabled(true);
        btn_eliminar.setEnabled(true);
         btn_agregar1.setEnabled(true);
        }
    }//GEN-LAST:event_cb_tipoItemStateChanged

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar1;
    private javax.swing.JButton btn_conexion;
    private javax.swing.JButton btn_datos;
    private javax.swing.JButton btn_ejecutar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_procedimientos;
    private javax.swing.JButton btn_sqlsentence;
    private javax.swing.JComboBox cb_tipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_entradas;
    private javax.swing.JTable tbl_result;
    private javax.swing.JTextField txt_nombreP;
    private javax.swing.JTextField txt_procedimiento;
    private javax.swing.JTextField txt_valor;
    // End of variables declaration//GEN-END:variables
}
