/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinaldb;

import logica.Conexion;
import logica.Estudiante;

/**
 *
 * @author Castro
 */
public class VentanaDatos extends javax.swing.JFrame{


    /**
     * Creates new form conexion
     */
     Conexion str_conn = new Conexion() ;
     Estudiante est=new Estudiante();
    public VentanaDatos() {
        initComponents();
           
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_cedula = new javax.swing.JLabel();
        txt_cedula = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        lbl_Nombre = new javax.swing.JLabel();
        txt_curso = new javax.swing.JTextField();
        lbl_curso = new javax.swing.JLabel();
        btn_guardarDatos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_conexion = new javax.swing.JButton();
        btn_procedimientos = new javax.swing.JButton();
        btn_datos = new javax.swing.JButton();
        btn_sqlsentence = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        lbl_cedula.setText("Cedula");

        txt_cedula.setName(""); // NOI18N

        lbl_Nombre.setText("Nombre");

        lbl_curso.setText("Curso");

        btn_guardarDatos.setText("Guardar");
        btn_guardarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarDatosActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Georgia", 2, 18)); // NOI18N
        jLabel1.setText("Datos Personales");

        btn_conexion.setText("String Conexion");
        btn_conexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_conexionActionPerformed(evt);
            }
        });

        btn_procedimientos.setText("Procedimientos");
        btn_procedimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_procedimientosActionPerformed(evt);
            }
        });

        btn_datos.setText("Datos Personales");

        btn_sqlsentence.setText("SQL Dinamico");
        btn_sqlsentence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sqlsentenceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_conexion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_procedimientos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_datos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_sqlsentence, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_cedula)
                        .addComponent(lbl_Nombre)
                        .addComponent(lbl_curso))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(4, 4, 4)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_curso)
                    .addComponent(txt_nombre)
                    .addComponent(txt_cedula)
                    .addComponent(btn_guardarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_cedula))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Nombre))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_curso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_curso))
                        .addGap(37, 37, 37)
                        .addComponent(btn_guardarDatos))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(btn_datos)
                        .addGap(18, 18, 18)
                        .addComponent(btn_conexion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_procedimientos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_sqlsentence)))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        lbl_cedula.getAccessibleContext().setAccessibleName("lbl_cedula");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_conexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_conexionActionPerformed
        // TODO add your handling code here:
         VentanaConexion strConexion = new VentanaConexion();
    
        strConexion.setVisible(true);
   
    }//GEN-LAST:event_btn_conexionActionPerformed

    private void btn_guardarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarDatosActionPerformed
        // TODO add your handling code here:
       
       
   
        
         str_conn.mostrar();
        int cedula=Integer.valueOf(txt_cedula.getText().toString().trim());
        String ced=txt_cedula.getText().toString();
        String nombre=txt_nombre.getText().toString().trim();
        String curso=txt_curso.getText().toString().trim();
        str_conn.insertar(ced,nombre,curso);
       
       System.out.println(cedula);	
       System.out.println("tamano nombre "+nombre.length());
     est.setEstudiante(cedula, nombre, curso);
        
    }//GEN-LAST:event_btn_guardarDatosActionPerformed

    private void btn_procedimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_procedimientosActionPerformed
        // TODO add your handling code here:
        VentanaProcedimientos pro = new VentanaProcedimientos();
         pro.setVisible(true);
    }//GEN-LAST:event_btn_procedimientosActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_formWindowClosed

    private void btn_sqlsentenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sqlsentenceActionPerformed

         VentanaSQLDinamico d= new  VentanaSQLDinamico();
            d.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btn_sqlsentenceActionPerformed

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_conexion;
    private javax.swing.JButton btn_datos;
    private javax.swing.JButton btn_guardarDatos;
    private javax.swing.JButton btn_procedimientos;
    private javax.swing.JButton btn_sqlsentence;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_Nombre;
    private javax.swing.JLabel lbl_cedula;
    private javax.swing.JLabel lbl_curso;
    private javax.swing.JTextField txt_cedula;
    private javax.swing.JTextField txt_curso;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
